version: '3.2'

services:
  wiremock-server:
    image: wiremock/wiremock 
    container_name: wiremock-server
    command: --extensions org.wiremock.webhooks.Webhooks --verbose
    volumes:
      - ./:/home/wiremock
      - ./extensions:/var/wiremock/extensions
    ports:
      - 8080:8080